import Character from "@/Types&Interfaces/Character";
import { mockFeats } from "./FeatsData";
import { mockSpells } from "./SpellData";

export const mockCharacters: Character[] = [
  {
    id: 1,
    name: 'Бизель',
    class: 'Жрица',
    subclass: 'Домен Жизни',
    race: 'Кованный',
    level: 4,
    currentHp: 25,
    maxHp: 25,
    tempHp: 4,
    speed: 9,
    abilities: {
      str: 12,
      dex: 12,
      con: 17,
      int: 9,
      wis: 16,
      cha: 8,
    },
    proficiencyBonus: 2,    
    /*resistances: ['яд'],
    immunities: ['болезнь'],
    vulnerabilities: [''],*/
    equipmentID: {armor : 1},
    weaponsID: 1,
    feats: [mockFeats[1]],
    spellcasting: {ability: "wis", slots: {1: {max: 4, current: 4}, 2: {max: 3, current: 3}}, spells: [], cantrips: []},
    classResources: [{name:"Божественный канал", current: 1, max: 1, shortRestRecovery: true, longRestRecovery: true}]
  },
  {
    id: 2,
    name: 'Дерек Грегори',
    class: 'Монах',
    subclass: 'Путь безмятежности',
    race: 'Человек',
    level: 4,
    currentHp: 26,
    maxHp: 26,
    tempHp: 0,
    speed: 9,
    abilities: {
      str: 12,
      dex: 16,
      con: 12,
      int: 11,
      wis: 16,
      cha: 10,
    },
    proficiencyBonus: 2,
    /*resistances: [''],
    immunities: [''],
    vulnerabilities: [''],*/
    equipmentID: {armor : 2},
    weaponsID: 1,  
    feats: [mockFeats[2]],
    classResources: [{name:"Очки ци", current: 4, max: 4, shortRestRecovery: true, longRestRecovery: true}]
  },
  {
    id: 3,
    name: 'Тень',
    class: 'Друидка',
    subclass: 'Круг звёзд',
    race: 'Лесная эльфийка',
    level: 4,
    currentHp: 28,
    maxHp: 28,
    tempHp: 0,
    speed: 9,
    abilities: {
      str: 9,
      dex: 14,
      con: 14,
      int: 11,
      wis: 16,
      cha: 11,
    },
    proficiencyBonus: 2,
    /*resistances: [''],
    immunities: [''],
    vulnerabilities: [''],*/
    equipmentID: {armor : 3},
    weaponsID: 1,  
    feats: [mockFeats[5]],
    spellcasting: {ability: "wis", slots: {1: {max: 4, current: 4}, 2: {max: 3, current: 3}}, spells: [], cantrips: []},
    classResources: [{name:"Звездная карта", current: 2, max: 2, shortRestRecovery: false, longRestRecovery: true},
                    {name:"Дикий облик", current: 2, max: 2, shortRestRecovery: true, longRestRecovery: true} ]
  },
  {
    id: 4,
    name: 'Грей',
    class: 'Плут',
    subclass: 'Сыщик',
    race: 'Кенку',
    level: 4,
    currentHp: 22,
    maxHp: 22,
    tempHp: 0,
    speed: 9,
    abilities: {
      str: 12,
      dex: 17,
      con: 10,
      int: 12,
      wis: 12,
      cha: 11,
    },
    proficiencyBonus: 2,
    /*resistances: [''],
    immunities: [''],
    vulnerabilities: [''],*/
    equipmentID: {armor : 5},
    weaponsID: 1,
    feats: [mockFeats[3]],
  },
  {
    id: 5,
    name: 'Аквалобыр',
    class: 'Варвар',
    subclass: 'Путь буревестника',
    race: 'Дварф',
    level: 4,
    currentHp: 40,
    maxHp: 40,
    tempHp: 0,
    speed: 7,
    abilities: {
      str: 15,
      dex: 10,
      con: 14,
      int: 10,
      wis: 13,
      cha: 10,
    },
    proficiencyBonus: 2,
    /*resistances: ['яд'],
    immunities: [''],
    vulnerabilities: [''],*/
    equipmentID: {armor : 4},
    weaponsID: 1,
    feats: [mockFeats[4]],
    classResources: [{name:"Заряды ярости", current: 3, max: 3, shortRestRecovery: false, longRestRecovery: true}]
  }
]