import Equipment from "@/Types&Interfaces/Equipment";

export const mockEquipment: Equipment[] = [
  // === Лёгкие доспехи ===
  {
    id: 1,
    name: 'Стёганая куртка',
    category: 'armor',
    acBonus: 0,
    abilityBonus: {},
    skillBonus: {},
    attackBonus: 0,
    description: '',
    armorType: 'light',
    baseAC: 11,
    maxDexBonus: null,
    stealthDisadvantage: true,
  },
  {
    id: 2,
    name: 'Кожаная куртка',
    category: 'armor',
    acBonus: 0,
    abilityBonus: {},
    skillBonus: {},
    attackBonus: 0,
    description: '',
    armorType: 'light',
    baseAC: 11,
    maxDexBonus: null,
    stealthDisadvantage: false,
  },
  {
    id: 3,
    name: 'Проклёпанная куртка',
    category: 'armor',
    acBonus: 0,
    abilityBonus: {},
    skillBonus: {},
    attackBonus: 0,
    description: '',
    armorType: 'light',
    baseAC: 12,
    maxDexBonus: null,
    stealthDisadvantage: false,
  },

  // === Средние доспехи ===
  {
    id: 4,
    name: 'Шкурная броня',
    category: 'armor',
    acBonus: 0,
    abilityBonus: {},
    skillBonus: {},
    attackBonus: 0,
    description: '',
    armorType: 'medium',
    baseAC: 12,
    maxDexBonus: 2,
    stealthDisadvantage: false,
  },
  {
    id: 5,
    name: 'Кольчатая броня',
    category: 'armor',
    acBonus: 0,
    abilityBonus: {},
    skillBonus: {},
    attackBonus: 0,
    description: '',
    armorType: 'medium',
    baseAC: 13,
    maxDexBonus: 2,
    stealthDisadvantage: false,
  },
  {
    id: 6,
    name: 'Чешуйчатая броня',
    category: 'armor',
    acBonus: 0,
    abilityBonus: {},
    skillBonus: {},
    attackBonus: 0,
    description: '',
    armorType: 'medium',
    baseAC: 14,
    maxDexBonus: 2,
    stealthDisadvantage: true,
  },
  {
    id: 7,
    name: 'Полулаты',
    category: 'armor',
    acBonus: 0,
    abilityBonus: {},
    skillBonus: {},
    attackBonus: 0,
    description: '',
    armorType: 'medium',
    baseAC: 15,
    maxDexBonus: 2,
    stealthDisadvantage: true,
  },
  {
    id: 8,
    name: 'Клёпанный доспех',
    category: 'armor',
    acBonus: 0,
    abilityBonus: {},
    skillBonus: {},
    attackBonus: 0,
    description: '',
    armorType: 'medium',
    baseAC: 14,
    maxDexBonus: 2,
    stealthDisadvantage: false,
  },

  // === Тяжёлые доспехи ===
  {
    id: 9,
    name: 'Кольчужная рубаха',
    category: 'armor',
    acBonus: 0,
    abilityBonus: {},
    skillBonus: {},
    attackBonus: 0,
    description: 'Требуется Сила 13',
    armorType: 'heavy',
    baseAC: 14,
    maxDexBonus: 0,
    stealthDisadvantage: true,
  },
  {
    id: 10,
    name: 'Кольчуга',
    category: 'armor',
    acBonus: 0,
    abilityBonus: {},
    skillBonus: {},
    attackBonus: 0,
    description: 'Требуется Сила 14',
    armorType: 'heavy',
    baseAC: 16,
    maxDexBonus: 0,
    stealthDisadvantage: true,
  },
  {
    id: 11,
    name: 'Наборный доспех',
    category: 'armor',
    acBonus: 0,
    abilityBonus: {},
    skillBonus: {},
    attackBonus: 0,
    description: 'Требуется Сила 15',
    armorType: 'heavy',
    baseAC: 17,
    maxDexBonus: 0,
    stealthDisadvantage: true,
  },
  {
    id: 12,
    name: 'Латы',
    category: 'armor',
    acBonus: 0,
    abilityBonus: {},
    skillBonus: {},
    attackBonus: 0,
    description: 'Требуется Сила 15',
    armorType: 'heavy',
    baseAC: 18,
    maxDexBonus: 0,
    stealthDisadvantage: true,
  },
  {
    id: 13,
    name: 'Деревянный щит',
    category: 'shield',
    acBonus: 1,
    abilityBonus: {},
    skillBonus: {},
    attackBonus: 0,
    description: 'Лёгкий',
    armorType: 'none',
    baseAC: 0,
    maxDexBonus: 0,
    stealthDisadvantage: false,
  },
  {
    id: 14,
    name: 'Средний щит (стандарт)',
    category: 'shield',
    acBonus: 2,
    abilityBonus: {},
    skillBonus: {},
    attackBonus: 0,
    description: '',
    armorType: 'none',
    baseAC: 0,
    maxDexBonus: null,
    stealthDisadvantage: false,
  },
  {
    id: 15,
    name: 'Большой железный',
    category: 'shield',
    acBonus: 3,
    abilityBonus: {},
    skillBonus: {},
    attackBonus: 0,
    description: 'Помеха на проверки Ловкости',
    armorType:'none',
    baseAC: 0,
    maxDexBonus: null,
    stealthDisadvantage: true,
  },
];