import Npc from "@/Types&Interfaces/Npc"

export const mockNpc: Npc[] = [
  {
    id: 101,
    name: 'Кобольд-порождение вампира',
    type: 'Нежить',
    ac: 14,
    maxHp: 40,
    currentHp: 40,
    speed: 9,
    initiativeMod: 4,
    abilities: {
      str: 10,
      dex: 18,
      con: 16,
      int: 8,
      wis: 8,
      cha: 8,
    },
    resistances: ['bludgeoning (non-magical)', 'piercing (non-magical)', 'slashing (non-magical)'],
    immunities: [],
    vulnerabilities: [],
    resources: [],
    proficiencyBonus: 2,
  },
  {
    id: 102,
    name: 'Черный кобольд драконий щит',
    type: 'Гуманоид',
    ac: 15,
    maxHp: 34,
    currentHp: 34,
    speed: 6,
    initiativeMod: 2,
    abilities: {
      str: 12,
      dex: 15,
      con: 14,
      int: 8,
      wis: 9,
      cha: 10,
    },
    resistances: ['acid'],
    immunities: [],
    vulnerabilities: [],
    resources: [],
    proficiencyBonus: 2,
  },
  {
    id: 103,
    name: 'Крылатый кобольд',
    type: 'Гуманоид',
    ac: 13,
    maxHp: 7,
    currentHp: 7,
    speed: 9,
    initiativeMod: 3,
    abilities: {
      str: 7,
      dex: 16,
      con: 9,
      int: 8,
      wis: 7,
      cha: 8,
    },
    resistances: [],
    immunities: [],
    vulnerabilities: [],
    resources: [],
    proficiencyBonus: 2,
  },
  {
    id: 104,
    name: 'Кобольд чешуйчатый чародей',
    type: 'Гуманоид',
    ac: 15,
    maxHp: 27,
    currentHp: 27,
    speed: 9,
    initiativeMod: 2,
    abilities: {
      str: 7,
      dex: 15,
      con: 14,
      int: 10,
      wis: 9,
      cha: 14,
    },
    resistances: [],
    immunities: [],
    vulnerabilities: [],
    resources: [{ name: 'Заклинания (2-й уровень)', current: 2, max: 2 }],
    proficiencyBonus: 2,
  },
  {
    id: 105,
    name: 'Наблюдатель',
    type: 'Аберрация',
    ac: 14,
    maxHp: 39,
    currentHp: 39,
    speed: 9,
    initiativeMod: 2,
    abilities: {
      str: 8,
      dex: 14,
      con: 14,
      int: 13,
      wis: 14,
      cha: 11,
    },
    resistances: [],
    immunities: [],
    vulnerabilities: [],
    resources: [],
    proficiencyBonus: 2,
  },
  {
    id: 106,
    name: 'Большой мимик',
    type: 'Монстр (перевертыш)',
    ac: 12,
    maxHp: 55,
    currentHp: 55,
    speed: 4.5,
    initiativeMod: 1,
    abilities: {
      str: 17,
      dex: 12,
      con: 15,
      int: 5,
      wis: 13,
      cha: 8,
    },
    resistances: [],
    immunities: ['acid'],
    vulnerabilities: [],
    resources: [],
    proficiencyBonus: 2,
  }
]