import Weapon from "@/Types&Interfaces/Weapon";

export const mockWeapons: Weapon[] = [
  {
    id: 1,
    name: 'Булава',
    description: 'Простое ближнее',
    damageDice: '1d6',
    damageType: 'дробящий',
    properties: [],
    attackBonus: 0,
    damageBonus: {},
    ability: 'str',
  },
  {
    id: 2,
    name: 'Кинжал',
    description: 'Простое ближнее',
    damageDice: '1d4',
    damageType: 'колющий',
    properties: ['фехтовальное', 'легкое', 'метательное (6/18 м)'],
    attackBonus: 0,
    damageBonus: {},
    ability: 'dex',
  },
  {
    id: 3,
    name: 'Дубинка',
    description: 'Простое ближнее',
    damageDice: '1d4',
    damageType: 'дробящий',
    properties: ['легкое'],
    attackBonus: 0,
    damageBonus: {},
    ability: 'str',
  },
  {
    id: 4,
    name: 'Ручной топор',
    description: 'Простое ближнее',
    damageDice: '1d6',
    damageType: 'рубящий',
    properties: ['легкое', 'метательное (6/18 м)'],
    attackBonus: 0,
    damageBonus: {},
    ability: 'str',
  },
  {
    id: 5,
    name: 'Серп',
    description: 'Простое ближнее',
    damageDice: '1d4',
    damageType: 'рубящий',
    properties: ['фехтовальное', 'легкое'],
    attackBonus: 0,
    damageBonus: {},
    ability: 'dex',
  },
  {
    id: 6,
    name: 'Посох',
    description: 'Простое ближнее',
    damageDice: '1d6',
    damageType: 'дробящий',
    properties: ['универсальное'],
    attackBonus: 0,
    damageBonus: {},
    ability: 'str',
  },
  {
    id: 7,
    name: 'Лёгкий молот',
    description: 'Простое ближнее',
    damageDice: '1d4',
    damageType: 'дробящий',
    properties: ['легкое', 'метательное (6/18 м)'],
    attackBonus: 0,
    damageBonus: {},
    ability: 'str',
  },
  {
    id: 8,
    name: 'Копьё',
    description: 'Простое ближнее',
    damageDice: '1d6',
    damageType: 'колющий',
    properties: ['универсальное', 'метательное (6/18 м)'],
    attackBonus: 0,
    damageBonus: {},
    ability: 'str',
  },

  // Воинское оружие
  {
    id: 9,
    name: 'Сай',
    description: 'Воинское ближнее',
    damageDice: '1d4',
    damageType: 'колющий',
    properties: ['легкое', 'фехтовальное'],
    attackBonus: 0,
    damageBonus: {},
    ability: 'dex',
    acBonus: 1,
  },
  {
    id: 10,
    name: 'Кусаригама',
    description: 'Воинское ближнее',
    damageDice: '1d6',
    damageType: 'рубящий',
    properties: ['фехтовальное', 'метательное (6/18 м)', 'особое: зацеп'],
    attackBonus: 0,
    damageBonus: {},
    ability: 'dex',
  },
  {
    id: 11,
    name: 'Короткий меч',
    description: 'Воинское ближнее',
    damageDice: '1d6',
    damageType: 'колющий',
    properties: ['фехтовальное', 'легкое'],
    attackBonus: 0,
    damageBonus: {},
    ability: 'dex',
  },
  {
    id: 12,
    name: 'Длинный меч',
    description: 'Воинское ближнее',
    damageDice: '1d8',
    damageType: 'рубящий',
    properties: ['универсальное'],
    attackBonus: 0,
    damageBonus: {},
    ability: 'str',
  },
  {
    id: 13,
    name: 'Двуручный меч',
    description: 'Воинское ближнее',
    damageDice: '2d6',
    damageType: 'рубящий',
    properties: ['двуручное', 'тяжелое'],
    attackBonus: 0,
    damageBonus: {},
    ability: 'str',
  },
  {
    id: 14,
    name: 'Рапира',
    description: 'Воинское ближнее',
    damageDice: '1d8',
    damageType: 'колющий',
    properties: ['фехтовальное'],
    attackBonus: 0,
    damageBonus: {},
    ability: 'dex',
  },
  {
    id: 15,
    name: 'Скимитар',
    description: 'Воинское ближнее',
    damageDice: '1d6',
    damageType: 'рубящий',
    properties: ['фехтовальное', 'легкое'],
    attackBonus: 0,
    damageBonus: {},
    ability: 'dex',
  },
  {
    id: 16,
    name: 'Катана',
    description: 'Воинское ближнее',
    damageDice: '1d8',
    damageType: 'рубящий',
    properties: ['универсальное', 'фехтовальное'],
    attackBonus: 0,
    damageBonus: {},
    ability: 'dex',
  },
  {
    id: 17,
    name: 'Нодати (двуручная катана)',
    description: 'Воинское ближнее',
    damageDice: '2d6',
    damageType: 'рубящий',
    properties: ['двуручное', 'тяжелое'],
    attackBonus: 0,
    damageBonus: {},
    ability: 'str',
  },
  {
    id: 18,
    name: 'Трезубец',
    description: 'Воинское ближнее',
    damageDice: '1d6',
    damageType: 'колющий',
    properties: ['универсальное', 'метательное (6/18 м)'],
    attackBonus: 0,
    damageBonus: {},
    ability: 'str',
  },
  {
    id: 19,
    name: 'Моргенштерн',
    description: 'Воинское ближнее',
    damageDice: '1d8',
    damageType: 'дробящий',
    properties: [],
    attackBonus: 0,
    damageBonus: {},
    ability: 'str',
  },
  {
    id: 20,
    name: 'Боевой молот',
    description: 'Воинское ближнее',
    damageDice: '1d8',
    damageType: 'дробящий',
    properties: ['универсальное'],
    attackBonus: 0,
    damageBonus: {},
    ability: 'str',
  },
  {
    id: 21,
    name: 'Боевой топор',
    description: 'Воинское ближнее',
    damageDice: '1d8',
    damageType: 'рубящий',
    properties: ['универсальное'],
    attackBonus: 0,
    damageBonus: {},
    ability: 'str',
  },
  {
    id: 22,
    name: 'Двуручная секира',
    description: 'Воинское ближнее',
    damageDice: '1d12',
    damageType: 'рубящий',
    properties: ['двуручное', 'тяжелое'],
    attackBonus: 0,
    damageBonus: {},
    ability: 'str',
  },
  {
    id: 23,
    name: 'Цеп (одноручный)',
    description: 'Воинское ближнее',
    damageDice: '1d8',
    damageType: 'дробящий',
    properties: [],
    attackBonus: 0,
    damageBonus: {},
    ability: 'str',
  },
  {
    id: 24,
    name: 'Кнут',
    description: 'Воинское ближнее',
    damageDice: '1d4',
    damageType: 'рубящий',
    properties: ['фехтовальное', 'досягаемость (3 м)'],
    attackBonus: 0,
    damageBonus: {},
    ability: 'dex',
  },
  {
    id: 25,
    name: 'Алебарда',
    description: 'Воинское ближнее',
    damageDice: '1d10',
    damageType: 'рубящий',
    properties: ['двуручное', 'тяжелое', 'досягаемость (3 м)'],
    attackBonus: 0,
    damageBonus: {},
    ability: 'str',
  },
  {
    id: 26,
    name: 'Глефа',
    description: 'Воинское ближнее',
    damageDice: '1d10',
    damageType: 'рубящий',
    properties: ['двуручное', 'тяжелое', 'досягаемость (3 м)'],
    attackBonus: 0,
    damageBonus: {},
    ability: 'str',
  },
  {
    id: 27,
    name: 'Двуручный молот',
    description: 'Воинское ближнее',
    damageDice: '2d6',
    damageType: 'дробящий',
    properties: ['двуручное', 'тяжелое'],
    attackBonus: 0,
    damageBonus: {},
    ability: 'str',
  },
  {
    id: 28,
    name: 'Пика',
    description: 'Воинское ближнее',
    damageDice: '1d10',
    damageType: 'колющий',
    properties: ['двуручное', 'тяжелое', 'досягаемость (3 м)'],
    attackBonus: 0,
    damageBonus: {},
    ability: 'str',
  },
  {
    id: 29,
    name: 'Клевец',
    description: 'Воинское ближнее',
    damageDice: '1d8',
    damageType: 'колющий',
    properties: ['универсальное'],
    attackBonus: 0,
    damageBonus: {},
    ability: 'str',
  },
  {
    id: 30,
    name: 'Пилум (дом.)',
    description: 'Воинское ближнее',
    damageDice: '1d6',
    damageType: 'колющий',
    properties: ['метательное (9/27 м)', 'ломается при броске'],
    attackBonus: 0,
    damageBonus: {},
    ability: 'str',
  },
  {
    id: 31,
    name: 'Нагината',
    description: 'Воинское ближнее',
    damageDice: '1d10',
    damageType: 'рубящий',
    properties: ['двуручное', 'тяжелое', 'досягаемость (3 м)'],
    attackBonus: 0,
    damageBonus: {},
    ability: 'str',
  },
  {
    id: 32,
    name: 'Коса (воинская)',
    description: 'Воинское ближнее',
    damageDice: '1d10',
    damageType: 'рубящий',
    properties: ['двуручное', 'тяжелое', 'досягаемость (3 м)', 'особое: сбивание с ног при критическом ударе'],
    attackBonus: 0,
    damageBonus: {},
    ability: 'str',
  },
];